service: notifications-lambda
frameworkVersion: '3'

provider:
  name: aws
  region: us-east-1
  runtime: dotnet8
  endpointType: regional 

plugins:
  - serverless-localstack

custom:
  localstack:
    stages:
      - local
    host: http://localhost
    edgePort: 4566

package:
  artifact: package.zip

functions:
  paymentNotification:
    handler: Notifications.Lambda::Notifications.Lambda.Adapters.Inbound.PaymentLambdaHandler::FunctionHandler
    events:
      - sqs:
          arn:
            Fn::GetAtt: [PaymentsQueue, Arn]

  userNotification:
    handler: Notifications.Lambda::Notifications.Lambda.Adapters.Inbound.UserLambdaHandler::FunctionHandler
    events:
      - sqs:
          arn:
            Fn::GetAtt: [UsersQueue, Arn]
resources:
  Resources:
    PaymentsQueue:
      Type: AWS::SQS::Queue
      Properties:
        QueueName: payments-2-queue
    UsersQueue:
      Type: AWS::SQS::Queue
      Properties:
        QueueName: users-queue