service: notifications-lambda
frameworkVersion: '3'

provider:
  name: aws
  region: us-east-1
  runtime: dotnet6
  endpointType: regional 

plugins:
  - serverless-localstack

custom:
  localstack:
    stages:
      - local
    host: http://localhost
    edgePort: 4566

package:
  artifact: lambda.zip

functions:
  paymentNotification:
    handler: Notifications.Lambda::Notifications.Lambda.Adapters.Inbound.PaymentLambdaHandler::FunctionHandler
    events:
      - sqs:
          arn: arn:aws:sqs:us-east-1:000000000000:payments-2-queue

  userNotification:
    handler: Notifications.Lambda::Notifications.Lambda.Adapters.Inbound.UserLambdaHandler::FunctionHandler
    events:
      - sqs:
          arn: arn:aws:sqs:us-east-1:000000000000:users-queue